### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by jhswedeveloper** [mhaddy/Slack-Webhook-for-MotionEye#1]
Hi thanks for the great script.

I'm a newbie but the issue im having is that when the motion is detected I believe it will send the last image to slack. 

The image I receive on slack is usually taken too late, so I often get images with no people in it. 

I think the duration should be around 5-10 seconds because after then the people are already gone from the camera frame. 

I'm trying to understand how to set the correct motion detection settings for 

* Motion gap = 20
* Captured Before = 10
* Captured After = 10
* Min motion frames = 20

I've tried different values but it doesn't seem to work well.

Do you have any suggestions?

**Comment by mhaddy** [comment]
Great question, @junhuhdev! The relevant snippet of code from multicam_slack.py that selects the image to post to Slack is:

```
	try:
		LATEST_FILE = max(LIST_OF_FILES, key=os.path.getctime)
		FILE_FOUND = 1
		logging.debug(LATEST_FILE)
```
As you're capturing 10 frames _before_ the most, you (I think) could iterate through the list of files and select the 10th one since motion was detected. This is going to be a guessing game though and sometimes you'll get lucky and others, you won't. 

What I'd recommend (and a future feature I'd like to build) is to run the images through an object detection algo that identifies animals or people. Look into https://aws.amazon.com/rekognition/ and https://cloud.google.com/vision as starting points.

**Comment by mhaddy** [comment]
Closing this one. Let me know if you have any other issues!
